//Imports
import commonjs from '@rollup/plugin-commonjs';
import resolve from '@rollup/plugin-node-resolve';
import threads from '../dist/es/index';

//Export
export default {
  input: 'entry.js',
  plugins: [
    resolve({
      browser: false,
      preferBuiltins: true,
      mainFields: [
        'main'
      ]
    }),
    commonjs(),
    threads({
      include: ['**/worker.js'],
      plugins: [
        resolve(),
        commonjs()
      ],
      external: [
        'events',
        'os',
        'path',
        'tty',
        'util'
      ]
    })
  ],
  output: [
    {
      dir: 'dist',
      format: 'cjs'
    }
  ],
  external: [
    'child_process',
    'events',
    'os',
    'path',
    'tty',
    'util'
  ],
  onwarn: (warning, warn) =>
  {
    //Hide eval warning generated by ThreadsJS
    if (warning.code != 'EVAL')
    {
      warn(warning);
    }
  }
};