# Continuous integration and delivery

name: CI/CD
on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test (Node V${{ matrix.node }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 15, 16]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install Modules
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Modules
        run: npm install

      - name: Build
        run: npm run build

      - name: Publish to NPM
        uses: pascalgn/npm-publish-action@1.3.8
        with:
          #See https://regexr.com/589ii for more information
          commit_pattern: "^v?(\\d+\\.\\d+\\.\\d+(?:-(?:alpha|beta)\\.\\d+)?)$"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
